### ISSUE TITLE
fitbit auth script needs an option to auth from headless box

### ISSUE THREAD

**Issue by kquinsland** [praveendath92/fitbit-googlefit#16]
I'm trying to set this sync utility u on a box that has no graphical environment.

In order to get the fitbit auth URL, i had to change line 55 
https://github.com/praveendath92/fitbit-googlefit/blob/master/auth/auth_fitbit.py#L55

to 

```
        #threading.Timer(1, webbrowser.open, args=(url,)).start()
        print(url)
```

which does not attempt to open the systems browser and just puts the auth URL on the console so i can open it on a device that does to obtain the fitbit auth token.

**Comment by praveendath92** [comment]
@kquinsland , Thanks for the info. I too think it's a good idea to turn it into a command line flag.

**Comment by Adirael** [comment]
I was halfway to implementing this (got the Fitbit auth working, and was about to start refactoring to be able to the Google part) and I though of a simpler solution:

Open an SSH tunnel to the server and then run the `auth_fitbit.py` script, commenting the`webbrowser.open` command and printing the URL.

Once authenticated the redirection will go through the tunnel to the server, everything works perfectly this way.

It may be a good thing to add a `--headless` flag or something of the like to display the URL instead of opening them, thus making this easier.

The command to open an SSH tunnel redirecting local 8080 to remote 8080 ports:

`ssh -L 8080:127.0.0.1:8080 <server-name>`

**Comment by kquinsland** [comment]
The google auth script needs no refactor; it prints the URL you should go
to.

SSH tunnels that forward traffic over a SOCKS proxy are not always
possible.  For when it's not:

When you get the fitbit auth URL from the console, all you need to do is
load up the URL in any browser and authenticate with your typical fitbit
user credentials (the sames ones you should have used to sign into the dev
console!)

That will walk you through the "are you sure you want to allow the app to
get your fitbit data?".  As soon as you click "connect" the URL in your
browser will be set to `localhost:8080/some-path-with-a-token`.


Copy that URL.
Open a new ssh session / open a new tmux pane .... etc
 on the machine running the fitbit auth script

then `curl "$the_auth_callback_url"` and then the listening fitbit auth
script will get the token it needs :).

**Comment by praveendath92** [comment]
@kquinsland Thanks for elaborating the process. I will integrate this into the authentication scripts, hopefully sometime next week. If you like to do this, I would be glad to merge your pull request 😄

**Comment by kquinsland** [comment]
Oh trust me, you dont want me writing Python code.  it's been a while  :).


-K

**Comment by praveendath92** [comment]
@kquinsland @Adirael and @bgtron Thanks for all your feedback. [Headless authetication](https://github.com/praveendath92/fitbit-googlefit#headless-authentication) is now added.
