### ISSUE TITLE
API Limit Reached & Failure Upon Retry

### ISSUE THREAD

**Issue by resolS** [praveendath92/fitbit-googlefit#21]
[ErrorLog.txt](https://github.com/praveendath92/fitbit-googlefit/files/734491/ErrorLog.txt)

* API Limit resets on the hour. I think this has changed. Appears app retries after 15mins.
* Upon retry I keep on getting errors, see attached.
* I tried manually setting it to sleep for over an hour, but it still throws an error.

**Comment by praveendath92** [comment]
@resolS , the latest commit should fix this issue.

**Comment by lightmaster** [comment]
I'm getting this issue, but no error. It runs through my date range until the API Limit is hit and then says it will retry at the next hour plus 1 second (ie: 18:00:01), however when that time comes around, it immediately says that the API Limit has been hit again and it will try at the top of the next hour. If I use Ctrl + C to stop it and retry again 5 minutes later, it proceeds successfully until it hits the API Limit again. (syncing 2 years, so gonna be hitting that limit a lot).

I believe that a difference of just a few seconds between the server the app is running on and Fitbit's server is causing the app to attempt to run a few seconds before the Fitbit's server resets the API Limit.

I propose changing the time that it attempts to run the next batch to 5 minutes after the hour to ensure that Fitbit's server's time is past the top of the hour mark.

**Comment by praveendath92** [comment]
@lightmaster In theory, that shouldn't happen because we are not using the time from the local clock directly. Fitbit tells us after how many seconds we can safely try again and we try after those many seconds. Given the delays in the network transmission, we will be waiting at least until the limit is reset. The only way we may try sooner is if the local clock drifts - counts seconds faster than the Fitbit servers. I don't see any issue with waiting a little bit longer as you suggested but I'm just curious about what's really causing the issue - clock drift is my best guess right now.
